// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MsgDanceScore = { type: string, beat: bigint, 
/**
 * Cumulative similarity scores for [player_1, player_2]. Range [0.0, 1.0].
 */
scores: [number, number], };
