// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MsgCommentaryAudio = { type: string, id: number, idx: number, mime: string, audio_b64: string, };
