// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Spectator snapshot sent on connect for an in-progress dance round.
 * Emitted by `DancePlugin::spectator_snapshot`. Lives next to the other
 * dance messages so the TS binding stays on the same ts-rs generation
 * path instead of drifting as a hand-written entry in shared/protocol.ts.
 */
export type MsgDanceSnapshot = { type: string, 
/**
 * Always "dance" — kept explicit so spectators can pre-narrow on it
 * before applying the rest of the fields.
 */
game_type: string, beat: number, 
/**
 * Cumulative similarity scores for [player_1, player_2]. Range [0.0, 1.0].
 */
scores: [number, number], };
