// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MsgDanceBeat = { type: string, beat: number, total_beats: number, 
/**
 * Per-keypoint data as [x, y, z, visibility]. Matches the json!() payload from
 * DancePlugin::on_tick: `[kp.x, kp.y, kp.z, kp.visibility]` per keypoint.
 */
target_pose: Array<[number, number, number, number]>, };
