// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoseKeypoint } from "./PoseKeypoint";

/**
 * Per-tick state broadcast for fps_boxing rooms.
 * Sent to each player containing their OPPONENT's 6 arm landmarks, both HP values, and round timer.
 * Two separate SendToPlayer events per tick — player 0 gets player 1's landmarks; player 1 gets player 0's.
 * Uses protocol::PoseKeypoint (has Serialize) NOT plugin_trait::PoseKeypoint (no Serialize).
 */
export type MsgFpsState = { type: "fps_state", left_shoulder: PoseKeypoint, right_shoulder: PoseKeypoint, left_elbow: PoseKeypoint, right_elbow: PoseKeypoint, left_wrist: PoseKeypoint, right_wrist: PoseKeypoint, 
/**
 * HP for both players: (player_1_hp, player_2_hp). Tuple renders as [number, number] in TypeScript.
 */
hp: [number, number], 
/**
 * Seconds remaining in the current round. ≤ 0.0 when time expires.
 */
round_timer: number, };
