// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MsgJoin = { type: "join", room_code: string, player_slot: 1 | 2, solo: boolean, };
