// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MsgLobbyUpdate = { type: string, p1: boolean, p2: boolean, 
/**
 * Identifies the game running in this room ("boxing", "fps_boxing",
 * "dance"). The spectator overlay uses this to pick which HUD to render
 * (HudLayer for boxing-like games, DanceHud for dance) — without it,
 * gameType stays null on the client and no HUD shows.
 */
game_type: string, };
