// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoseKeypoint } from "./PoseKeypoint";

export type MsgPoseUpdate = { type: "pose_update", player: 1 | 2, keypoints: Array<PoseKeypoint>, };
