// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MsgRoundEnd = { type: "round_end", 
/**
 * null means draw; 1 or 2 is the winning player
 */
winner: 1 | 2 | null, final_hp: [number, number], };
